### PR TITLE
change version to 0.0.2

### PR DESCRIPTION
**Pull request by CubeyTheCube**
because

(joe told me to make this pr)

### CODE REVIEW

**Comment by gosoccerboy5** [comment]
who's joe?

**Comment by FunctionalMetatable** [comment]
> who's joe?

idk

**Comment by FunctionalMetatable** [comment]
> who's joe?

also would you like to join da org

**Comment by gosoccerboy5** [comment]
> > who's joe?
> 
> also would you like to join da org

Maybe? I don't know if I would be able to contribute much 😅 , but OK

**Pull request merged**
